- hosts: docker
  tasks:
     - name: stop container
       shell: docker container stop dockeradja1
     - name: remove container
       shell: docker container rm dockeradja1
     - name: docker image removal
       shell: docker image rm -f oalalif/gadja2.1
     - name: create new container
       shell: docker run -itd --name dockeradja1 oalalif/gadja2.1